/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#133444",
        "primary-fixed-dim": "#b2ccc7",
        "on-error-container": "#ffdad6",
        "outline": "#8c9290",
        "primary": "#b2ccc7",
        "on-primary-container": "#718985",
        "surface-variant": "#343534",
        "surface-tint": "#b2ccc7",
        "inverse-primary": "#4b635f",
        "surface-container-highest": "#343534",
        "surface-dim": "#121413",
        "on-secondary-fixed": "#001e2c",
        "on-tertiary": "#432a26",
        "surface-container-low": "#1b1c1b",
        "on-tertiary-container": "#9e7c77",
        "tertiary": "#e5bdb8",
        "on-background": "#e3e2e1",
        "tertiary-fixed": "#ffdad5",
        "on-error": "#690005",
        "outline-variant": "#424847",
        "secondary": "#abcbdf",
        "on-tertiary-fixed-variant": "#5c403c",
        "surface-container": "#1f201f",
        "primary-container": "#08201d",
        "on-secondary-container": "#9dbdd0",
        "error": "#ffb4ab",
        "secondary-fixed": "#c7e7fc",
        "inverse-surface": "#e3e2e1",
        "on-primary": "#1e3431",
        "background": "#121413",
        "tertiary-fixed-dim": "#e5bdb8",
        "secondary-fixed-dim": "#abcbdf",
        "tertiary-container": "#2c1613",
        "on-surface": "#e3e2e1",
        "inverse-on-surface": "#303130",
        "surface-bright": "#383939",
        "error-container": "#93000a",
        "surface-container-high": "#292a2a",
        "surface-container-lowest": "#0d0e0e",
        "on-tertiary-fixed": "#2b1613",
        "secondary-container": "#2e4d5d",
        "on-primary-fixed-variant": "#344b47",
        "on-surface-variant": "#c1c8c6",
        "on-secondary-fixed-variant": "#2c4a5b",
        "surface": "#121413",
        "primary-fixed": "#cee8e3",
        "on-primary-fixed": "#071f1c"
      },
      fontFamily: {
        "display-lg": ["Anybody", "sans-serif"],
        "label-bold": ["Rubik", "sans-serif"],
        "body-lg": ["Rubik", "sans-serif"],
        "headline-md": ["Anybody", "sans-serif"],
        "body-md": ["Rubik", "sans-serif"],
        "headline-sm": ["Anybody", "sans-serif"]
      },
      spacing: {
        "lg": "48px",
        "gutter": "20px",
        "md": "24px",
        "xl": "80px",
        "base": "8px",
        "sm": "12px",
        "xs": "4px"
      }
    },
  },
  plugins: [],
}
